dataset:
  path: "/home/yeqchen/cap/CAP/dataset/BirdMigration/bird_data.txt"
  batch_size: 32
  train_size: 0.8
  valid_size: 0.1
  test_size: 0.1

model:
  type: "transformer"
  hidden_dim: 128
  num_layers: 2
  dropout: 0.1

training:
  epochs: 50
  learning_rate: 0.5
  patience: 5
  device: "cuda"
