dataset:
  path: "dataset/long_term_forecast/ETT-small/ETTm2.csv"
  batch_size: 32
  train_size: 0.8
  valid_size: 0.1
  test_size: 0.1
  normalization: true

model:

  type: "informer"
  d_model: 512
  seq_len: 96
  pred_len: 96
  num_layers: 2
  dropout: 0.1
  d_ff: 2048

training:
  epochs: 10
  learning_rate: 0.0001
  patience: 3
  device: "cuda"
